### ISSUE TITLE
annotated with @ViewType.

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/AnnotatedAdapter#13]
Hello,
I am getting the following compilation error:

Error:(30, 37) error: mHousecalls in HistoryListAdapter is not public. Only final integer fields with public visibility can be annotated with @ViewType.
This does not make sense to me. Please elaborate...

Igor

**Comment by IgorGanapolsky** [comment]
mHousecalls is of type List.  This error is very unclear.

**Comment by sockeqwe** [comment]
I think there is a general misunderstanding of ViewTypes:

In general `RecyclerView.Adapter` provides a way to distinguish between different Layouts per row.
For instance you want to display a List of `Fruits`:

```java
public class Fruit {  ... }

public class Apple extends Fruit { ... }

public class Pear extends Fruit { ... }
``` 

So you want to display `List<Fruit>` in a `RecyclerView`  but you want that the Apples are displayed by using `R.layout.item_apple` while Pear should be displayed by using `R.layout.item_pear`. `RecyclerView.Adapter` can handle that for you. You have to create two "ViewTypes". A "ViewType" is basically just a unique (per adapter) integer. How would you implement that if you have to write such an adapter by hand (not by using AnnotatedAdapter):

```java
public class FruitsAdapter extends RecyclerView.Adapter<RecyclerView.ViewHolder> {
    class AppleViewHolder extends RecyclerView.ViewHolder {
        ...
    }

    class PearViewHolder extends RecyclerView.ViewHolder {
        ...
    }

    private List<Fruit> items;

   private final int VIEW_TYPE_APPLE = 0;
   private final int VIEW_TYPE_PEAR = 1;


    @Override
    public int getItemViewType(int position) {
        Fruit fruit = items.get(position);
        if (fruit instanceof Apple) 
           return VIEW_TYPE_APPLE;
        else
            return VIEW_TYPE_PEAR;
    }

    @Override
    public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
         
           if (viewType == VIEW_TYPE_APPLE)
               return new AppleViewHolder( inflater.inflate(R.layout.item_apple) );
           else 
              return new PearViewHolder( inflater.inflate(R.layout.item_pear) );
    }

  @Override
  public final void bindViewHolder (ViewHolder vh, int position) {
       
        int viewType = getItemViewType(position);
     
       if (viewType == VIEW_TYPE_APPLE) {
          Apple apple = (Apple) items.get(position);
          AppleViewHolder viewHolder = (AppleViewHolder) vh;
          // ... display data through apple layout
       } else {
          Pear pear = (Pear) items.get(position);
          PearViewHolder viewHolder = (PearViewHolder) vh;
          // ... display data through pear layout
       }
   }
}
```


`AnnotatedAdpater` basically generates that kind of code for distinguish between different ViewTypes  and the code for ViewHolders for you. The same Adapter with `AnnotatedAdapter` looks like this:
```java
public class FruitsAdapter extends SupportAnnotatedAdapter  implements FruitsAdapterBinder {

     @ViewType ( layout = R.layout.item_apple, ... )
     public final int apple = 0;

     @ViewType ( layout = R.layout.item_pear, ... )
     public final int pear = 1;

      private List<Fruit> items;

     ...
}

``` 

So you have to annotated the "ViewTypes" and not the list of of items. If you have just one view type (i.e. you list is displaying all items in the same way) you still have to define one view type:

```java
public class AppleAdapter extends SupportAnnotatedAdapter  implements AppleAdapterBinder {

     @ViewType ( layout = R.layout.item_apple, ... )
     public final int apple = 0;

      private List<Apple> items;

     ...
}

``` 

Hope that helps

**Comment by IgorGanapolsky** [comment]
>you still have to define one view type

I already have this:
`@ViewType(
            layout = R.layout.item_history,
            fields = {
                    @Field(id = R.id.itemDate, type = TextView.class, name = "itemDate"),
                    @Field(id = R.id.itemPatientName, type = TextView.class, name = "itemPatientName"),
                    @Field(id = R.id.itemPatientAge, type = TextView.class, name = "itemPatientAge"),
                    @Field(id = R.id.itemIllness, type = TextView.class, name = "itemIllness"),
                    @Field(id = R.id.itemProvider, type = TextView.class, name = "itemProvider"),
            })

So what do you mean by defining one view type?
The only thing that makes this error go away is putting the following line:
`    public final int item= 0;`

That makes no sense, since this variable isn't necessarily used anywhere in the class.  Are you saying it is mandatory to declare this variable?


`

**Comment by sockeqwe** [comment]
In short: yes it's mandatory to declare this variable. 

This variable is used internally by the generated code.

**Comment by IgorGanapolsky** [comment]
I see.  Thanks!
