### ISSUE TITLE
RecyclerViews positional click

### ISSUE THREAD

**Issue by ersin-ertan** [sockeqwe/AnnotatedAdapter#16]
Hey Hannes, how would a click listener work with positional clicks, similar to listviews? 
I have tried the sample and have gotten to the point where I can differentiate between types of clicks(text, and image).

https://github.com/ersin-ertan/SpotifyStreamer/blob/master/spotifystreamer2/src/main/java/com/nullcognition/spotifystreamer/SampleAdapter.java#L49-L71

**Comment by sockeqwe** [comment]
Im not sure if I understood your problem correctly, but typically I do something like this:
```java
public class SampleAdapter extends SupportAnnotatedAdapter
		implements SampleAdapterBinder {

      static class MyClickListener implements OnClickListener {
           
            public String dataItem;

            public void onClick(View v){
                  // Do something --> dataItem is the underlying data
            }
      }


	@ViewType(
			initMethod = true,
			layout = R.layout.row_with_pic,
			views = {
					@ViewField(id = R.id.textView, name = "text", type = TextView.class),
					@ViewField(id = R.id.imageView, name = "image", type = ImageView.class)
			},
			fields = {
					@Field(
							type = MyClickListener.class,
							name = "clickListener"
					)
			}
	)
	public final int rowWithPic = 0;

      @Override
       public void initViewHolder(SampleAdapterHolders.RowWithPicViewHolder vh, View view, ViewGroup parent) {
		vh.clickListener = new MyClickListener();
		vh.itemView.setOnClickListener(vh.clickListener);  // sets click listener to whole view, you could replace that with vh.text.setOnClickListener(vh.clickListener) or whatever you want to achieve.
      }

      @Override
      public void bindViewHolder(SampleAdapterHolders.RowWithPicViewHolder vh, int position){

		String str = items.get(position);
		vh.text.setText(str);
		vh.text.setOnClickListener(this);
		vh.image.setOnClickListener(this);
		vh.image.setImageResource(R.drawable.abc_btn_rating_star_off_mtrl_alpha);
		vh.clickListener.dataItem =  str;
	}

    ...
}
```

**Comment by ersin-ertan** [comment]
Thanks, I was able to get the functionality for the position with [something similar](https://github.com/ersin-ertan/SpotifyStreamer/blob/80322726e88292f199d4bc2c5a479099975f124a/spotifystreamer2/src/main/java/com/nullcognition/spotifystreamer/SampleAdapter.java) to the above code; minus initViewHolder (not a method of recyclerview.SupportAnnotatedAdapter), and other minor modifications.

**Comment by sockeqwe** [comment]
```java
vh.clickListener.position = position;
```
That only works  as long as you don't change the adapters dataset, since bindViewHolder() will not be called again for views that are already displayed on screen.

**Comment by IgorGanapolsky** [comment]
Unfortunately `initViewHolder` doesn't compile.  The @Override complains: 
> Method does not override method from its superclaass

**Comment by sockeqwe** [comment]
Then you simply have not implemented the correct method. Use quickfix in android studio to let android studio implement the method skeleton for you. Also keep in mind that you may have to rebuild (recompile) your project if you change your annotations.

**Comment by IgorGanapolsky** [comment]
@sockeqwe Looking at sourcecode for support-recyclerview-1.1.1-sources SupportAnnotatedAdapter, I do not see a an `onInitiViewHolder` method in there.  Should there be one?

**Comment by sockeqwe** [comment]
The `onInitiViewHolder()` methods gets generated if you set it explicitly in your annotation:
```java
@ViewType(
            initMethod = true,
            ...
```

**Comment by IgorGanapolsky** [comment]
@sockeqwe Thanks for the help, I wouldn't have figured this out on my own as there are some moving parts here.  Keep making AnnotatedAdapter better!  @changetip $1.

**Comment by changetip** [comment]
Hi @sockeqwe, @IgorGanapolsky sent you a tip worth 4,079 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/904083)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
