### ISSUE TITLE
RecyclerView as ViewField

### ISSUE THREAD

**Issue by IgorGanapolsky** [sockeqwe/AnnotatedAdapter#19]
Hello,
is it possible to define a RecyclerView as a @ViewField?  Like this:
`@ViewField(id = R.id.chargersRecyclerView, type = RecyclerView.class,
                            name = "chargersRecyclerView")`
Currently when I do this, it doesn't show up on the screen.

Please advise,
Igor

**Comment by sockeqwe** [comment]
Yes, it should work.

So your ViewHolder's layout contains a RecyclerView, is  that what you want to achieve?

**Comment by IgorGanapolsky** [comment]
Correct, that is what I want to achieve.  However, I think the problem is that a nested RecyclerView will not show any data if it has `match_parent` for its width & height.  Have you run across this kind of issue?

**Comment by sockeqwe** [comment]
Yep, it's definitely not a problem of this library. You explicitly have to set a height (or width, depending on the scroll axis of the parent recycler view) to a concrete value.
